export const initialData: Movie = {
    _id: -1,
    title: "",
    year: "",
    runtime: "",
    type: "",
    poster: "",
    released: "",
    imdbRating: "",
    genre: "",
    actors: "",
    writer: "",
    director: "",
    plot: "",
    country: "",
}